jobs:
  run_bot:
    runs-on: ubuntu-latest
    name: run_bot
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: get
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"
          architecture: "x64"
      - run: pip install -r ./requirements.txt && python ./run.py

    env:
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      USER_INFO: ${{secrets.USER_INFO}}

name: run_bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1,2,3,4,5,6,7,8,9,10 * *"
